POST http://localhost:3000/reports
Content-Type: application/json

{
  "maker": "hyundai",
  "model": "grandeur",
  "year": 2025,
  "mileage": 10000,
  "latitude": 0,
  "longitude": 0,
  "price": 100000
}